apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  annotations:
    manifestival: new
  creationTimestamp: "2020-04-01T13:25:07Z"
  generation: 1
  name: openshift-client
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Config
    name: cluster
    uid: 29a425db-2f4b-44e3-827a-c4bcff69dca4
  resourceVersion: "85845"
  selfLink: /apis/tekton.dev/v1alpha1/clustertasks/openshift-client
  uid: ffb33c56-31ac-4da0-ad4d-e2a3a79a580b
spec:
  inputs:
    params:
    - default:
      - help
      description: The OpenShift CLI arguments to run
      name: ARGS
      type: array
  steps:
  - args:
    - $(inputs.params.ARGS)
    command:
    - /usr/bin/oc
    image: quay.io/openshift/origin-cli:latest
    name: oc
    resources: {}
