apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    manifestival: new
  creationTimestamp: "2020-04-01T13:41:47Z"
  generation: 1
  name: java-spring-boot2-build-pl
  namespace: kabanero
  ownerReferences:
  - apiVersion: kabanero.io/v1alpha2
    controller: false
    kind: Stack
    name: java-spring-boot2
    uid: 4ee1ace2-2196-4c47-8fe7-b004cbdd20d5
  resourceVersion: "100129"
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/kabanero/pipelines/java-spring-boot2-build-pl
  uid: 46d60c49-420d-46c0-89ca-8d646b2f059d
spec:
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: validate-stack-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
    taskRef:
      kind: Task
      name: java-spring-boot2-validate-stack-task
  - name: build-task
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: docker-image
        resource: docker-image
    runAfter:
    - validate-stack-task
    taskRef:
      kind: Task
      name: java-spring-boot2-build-task
