apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  annotations:
    manifestival: new
  creationTimestamp: "2020-04-01T13:41:46Z"
  generation: 1
  name: java-spring-boot2-image-retag-pl
  namespace: kabanero
  ownerReferences:
  - apiVersion: kabanero.io/v1alpha2
    controller: false
    kind: Stack
    name: java-spring-boot2
    uid: 4ee1ace2-2196-4c47-8fe7-b004cbdd20d5
  resourceVersion: "100111"
  selfLink: /apis/tekton.dev/v1alpha1/namespaces/kabanero/pipelines/java-spring-boot2-image-retag-pl
  uid: b16bd2e5-0a06-4aa4-b99c-c1c10cd4898a
spec:
  resources:
  - name: docker-src-image
    type: image
  - name: docker-dest-image
    type: image
  tasks:
  - name: image-retag-task
    resources:
      inputs:
      - name: docker-src-image
        resource: docker-src-image
      - name: docker-dest-image
        resource: docker-dest-image
      outputs:
      - name: docker-dest-image
        resource: docker-dest-image
    taskRef:
      kind: Task
      name: java-spring-boot2-image-retag-task
